// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gmb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LevelSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsLevelSnapshot(buf []byte, offset flatbuffers.UOffsetT) *LevelSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LevelSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishLevelSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLevelSnapshot(buf []byte, offset flatbuffers.UOffsetT) *LevelSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LevelSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLevelSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LevelSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LevelSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LevelSnapshot) Dimension() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LevelSnapshot) GameTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LevelSnapshot) MutateGameTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *LevelSnapshot) DayTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LevelSnapshot) MutateDayTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *LevelSnapshot) Raining() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LevelSnapshot) MutateRaining(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *LevelSnapshot) Thundering() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LevelSnapshot) MutateThundering(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func LevelSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func LevelSnapshotAddDimension(builder *flatbuffers.Builder, dimension flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dimension), 0)
}
func LevelSnapshotAddGameTime(builder *flatbuffers.Builder, gameTime int64) {
	builder.PrependInt64Slot(1, gameTime, 0)
}
func LevelSnapshotAddDayTime(builder *flatbuffers.Builder, dayTime int64) {
	builder.PrependInt64Slot(2, dayTime, 0)
}
func LevelSnapshotAddRaining(builder *flatbuffers.Builder, raining bool) {
	builder.PrependBoolSlot(3, raining, false)
}
func LevelSnapshotAddThundering(builder *flatbuffers.Builder, thundering bool) {
	builder.PrependBoolSlot(4, thundering, false)
}
func LevelSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
